In [ ]:
import cv2
import numpy as np

img=cv2.imread('flower1.jpg',0)
int_min=np.amin(img)
int_max=np.amax(img)
x1=int_min
y1=0
x2=int_max
y2=255
m=float(y2-y1)/float(x2-x1)
out=img*m
out=out-(x1*m)

out=np.array(out, dtype = np.uint8)
print(img)
print(out)
cv2.imshow('image', img)
cv2.imshow('contrast expanded', out)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[126 126 126 ... 128 128 128]
 [126 126 126 ... 128 128 128]
 [126 126 127 ... 128 129 129]
 ...
 [135 135 134 ... 114 114 113]
 [133 134 133 ... 114 113 113]
 [134 136 134 ... 114 113 113]]
[[122 122 122 ... 124 124 124]
 [122 122 122 ... 124 124 124]
 [122 122 123 ... 124 125 125]
 ...
 [131 131 130 ... 110 110 108]
 [129 130 129 ... 110 108 108]
 [130 132 130 ... 110 108 108]]
