In [4]:
from sklearn.decomposition import PCA
import numpy as np

In [5]:
data = np.array([[1,2,1],[1,0,2],[1,3,1]])

data

array([[1, 2, 1],
       [1, 0, 2],
       [1, 3, 1]])

In [6]:
pca = PCA(n_components=2)

In [13]:
transformed_data = pca.fit_transform(data)

In [14]:
transformed_data

array([[-0.42689895,  0.19994877],
       [ 1.79406947, -0.05947228],
       [-1.36717052, -0.14047649]])

In [15]:
x_approx = pca.inverse_transform(transformed_data)

In [16]:
x_approx

array([[1.00000000e+00, 2.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.99840144e-15, 2.00000000e+00],
       [1.00000000e+00, 3.00000000e+00, 1.00000000e+00]])